import { createElement } from 'lwc';
import ApiDecoratorParentEx7 from 'c/apiDecoratorParentEx7';

describe('c-api-decorator-parent-ex7', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-api-decorator-parent-ex7', {
            is: ApiDecoratorParentEx7
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});